server:
  port: 8930
spring:
  application:
    name: service-integral
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true # 意思是后来发现的bean会覆盖之前相同名称的bean
  redis:
    redisson:
      file: classpath:redisson.yml
  kafka:
    client-id: service-integral
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 3
      acks: all
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    streams:
      replication-factor: 3
    consumer:
      enable-auto-commit: false
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: defaultConsumerGroup
      auto-offset-reset: earliest
      auto-commit-interval: 1000
    listener:
      ack-mode: MANUAL_IMMEDIATE
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

#Sharding Sphere 不支持数据库健康检查，关闭actuate 的数据库健康检查即可。
management:
  health:
    db:
      enabled: false
sharding:
  jdbc:
    datasource:
      names: defaultds,ds0,ds1,ds2,ds3
      defaultds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_cloud_framework?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
        username: root
        password: 81ce7571cf55f1aa41d6d9d5d7f25b09415fee188a720f13b0ef686f183b2f17
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/service_integral_1?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
        username: root
        password: 81ce7571cf55f1aa41d6d9d5d7f25b09415fee188a720f13b0ef686f183b2f17
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/service_integral_2?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
        username: root
        password: 81ce7571cf55f1aa41d6d9d5d7f25b09415fee188a720f13b0ef686f183b2f17
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/service_integral_3?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
        username: root
        password: 81ce7571cf55f1aa41d6d9d5d7f25b09415fee188a720f13b0ef686f183b2f17
      ds3:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/service_integral_4?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
        username: root
        password: 81ce7571cf55f1aa41d6d9d5d7f25b09415fee188a720f13b0ef686f183b2f17
    config:
      props:
        sql.show: true
      sharding:
        default-data-source-name: defaultds
        tables:
          integral_record:
            tableStrategy:
              standard:
                shardingColumn: create_by
                precise-algorithm-class-name: com.cloud.integral.config.IntegralTableStrategy
            databaseStrategy:
              standard:
                shardingColumn: create_by
                precise-algorithm-class-name: com.cloud.integral.config.IntegralDatabaseStrategy
